# .air.toml configuration file

# Root directory
root = "."
tmp_dir = "tmp"
debug = false
cmd = "go run ./cmd/main.go"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main ./cmd/main.go"
# Add other files or directories to watch for changes
include_ext = ["go", "tpl", "tmpl", "html", "sql", "js", "ts", "css", "env"]
exclude_dir = ["tmp", "vendor", "internal/repository/mocks"]

[log]
level = "debug"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[dirs]
# Watching the internal directory and db directory for changes
watch_dir = [
    "cmd",
    "internal",
    "db"
]

[watch]
# Ignore certain files or directories
exclude_dir = ["tmp", "vendor"]

# Extensions to watch
include_ext = ["go"]

# Files to exclude
exclude_file = ["go.sum", "go.mod"]

# Interval for polling changes (in milliseconds)
delay = 1000

[deploy]
bin = "cmd/main.go"
