# .air.toml configuration file

# Root directory
root = "."
tmp_dir = "tmp"
debug = false
cmd = "go run ./main.go"

[build]
bin = "tmp/main"
cmd = "go build -o tmp/main ./main.go"
include_ext = ["go", "tpl", "tmpl", "html", "sql", "js", "ts", "css", "env"]
exclude_dir = ["tmp", "vendor", "internal/repository/mocks", "codeFiles"]

[log]
level = "debug"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[dirs]
# Watching the internal directory and db directory for changes
watch_dir = [
    ".",
    "internal",
    "db"
]

[watch]
# Ignore certain files or directories
exclude_dir = ["tmp", "vendor", "codeFiles"]

# Extensions to watch
include_ext = ["go", "tpl", "tmpl", "html", "sql", "js", "ts", "css", "env"]

# Files to exclude
exclude_file = ["go.sum", "go.mod"]

# Interval for polling changes (in milliseconds)
poll = true

[deploy]
bin = "main.go"